apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: 1kstep/dingus:latest
    name: nginx-dingus
    env:
    - name: VAULT_ADDR
      value: "http://192.168.1.230:8200"
    - name: VAULT_TOKEN
      value: root
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  serviceAccountName: internal-app
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 7200
          audience: vault
